### ISSUE TITLE
make this better!

### ISSUE THREAD

**Issue by jameswillett** [GillisWerrebrouck/text-extract#1]
https://github.com/GillisWerrebrouck/text-extract/blob/master/index.js#L61-L64

this can be `const topicName = config[detection.language === lang ? 'RESULT_TOPIC' : 'TRANSLATE_TOPIC'];` dude!!!!

https://github.com/GillisWerrebrouck/text-extract/blob/master/index.js#L100

you dont need to return this resolved promise here!!!!! you can just return it `if file.resourceState === 'not_exists'`!!!! 

https://github.com/GillisWerrebrouck/text-extract/blob/master/index.js#L42

youre using node 8! embrace `async await`!!!!!! clean up your scope!!!! END MUTATION

https://github.com/GillisWerrebrouck/text-extract/blob/master/index.js#L53-L56

```
.then(([d]) => {
  const detection = Array.isArray(d) ? d[0] : d;
  ...
```
duh

https://github.com/GillisWerrebrouck/text-extract/blob/master/index.js#L65-L69

OBJECT SHORT HAND!!!!!!!!!!

```
const messageData = { text, filename, lang };
```

**Comment by jameswillett** [comment]
FEEL FREE TO JUST DELETE THIS ISSUE INSTEAD OF CLOSING IT SO NO ONE ELSE CAN SEE IT BUT YOU

**Comment by rjschwartz** [comment]
Too late.

**Comment by GillisWerrebrouck** [comment]
Nooooo
![why](https://user-images.githubusercontent.com/9055308/52597356-07d3e000-2e53-11e9-81eb-b460d3da50eb.gif)

Hi @rjschwartz
